title: "Nyrosys"
email: "nyrosys@gmail.com"
description: "Conseil & Automatisation IT — Strasbourg"
url: "https://nyrosys.fr"
lang: fr
locale: fr-FR
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

# Options
title-separator: "-"
breadcrumbs: true
